apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  # namespace: frontend
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: gcr.io/optimum-task-429215-h2/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "34.123.154.45"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "ica4"

---
apiVersion: v1
kind: Service
metadata:
  name: react-app
  # namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
